/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HJVO5pcXCFN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Gabarito } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function landing() {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-[#F5F5F5] relative overflow-hidden">
      <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 flex">
        <div className="w-[400px] h-[400px] rounded-full bg-[#6366F1] opacity-30 blur-[100px] mr-[-150px]" />
        <div className="w-[400px] h-[400px] rounded-full bg-[#7C3AED] opacity-30 blur-[100px]" />
      </div>
      <main className="flex-1 flex flex-col items-center justify-center px-4 md:px-6 py-12 md:py-24 lg:py-32 xl:py-48 text-center">
        <div className="max-w-md space-y-4">
          <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tighter">Unleash the Power of AI</h1>
          <p className="text-muted-foreground md:text-xl">
            Our upcoming AI app will revolutionize the way you work. Join our waiting list to be the first to experience
            it.
          </p>
          <form className="flex gap-2 w-full">
            <Input type="email" placeholder="Enter your email" className="flex-1" />
            <Button type="submit">Join Waitlist</Button>
          </form>
        </div>
      </main>
      <footer className="py-6 w-full shrink-0 border-t text-xs text-muted-foreground flex items-center justify-between px-4 md:px-6">
        <p>&copy; 2024 AI App. All rights reserved.</p>
        <nav className="flex gap-4">
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Terms
          </Link>
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}
